In [1]:
import pandas as pd

In [4]:
df=pd.read_csv("Retail sales.csv")
df.head()

   Order Date        Product     Category Region  Quantity  Sales  Profit
0  02-11-2026  Laptop Pro 15  Electronics   east         3   4500     900
1  03-10-2026          Chair    Furniture   west         7   1250     250
2  04-06-2026   Smartphone X    Appliance  north         5   7000    1400
3  05-05-2026   Coffee Maker    Appliance  south         8    600     120
4  06-11-2026      Desk Lamp    Furniture   west         9    320      64

In [5]:
df=pd.read_csv("Retail sales.csv")
#df.head()
df.info()
#df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order Date  10 non-null     object
 1   Product     10 non-null     object
 2   Category    10 non-null     object
 3   Region      10 non-null     object
 4   Quantity    10 non-null     int64
 5   Sales       10 non-null     int64
 6   Profit      10 non-null     int64
dtypes: int64(3), object(4)
memory usage: 692.0+ bytes

In [7]:
df=pd.read_csv("Retail sales.csv")
#df.head()
#df.info()
df.isnull().sum()

Order Date    0
Product       0
Category      0
Region        0
Quantity      0
Sales         0
Profit        0
dtype: int64

In [10]:
### CATEGORICAL MISSING VALUES
df=pd.read_csv("Retail sales.csv")
df['Region'].fillna(df['Region'].mode()[0])
print(df)

   Order Date        Product     Category Region  Quantity  Sales  Profit
0  02-11-2026  Laptop Pro 15  Electronics   east         3   4500     900
1  03-10-2026          Chair    Furniture   west         7   1250     250
2  04-06-2026   Smartphone X    Appliance  north         5   7000    1400
3  05-05-2026   Coffee Maker    Appliance  south         8    600     120
4  06-11-2026      Desk Lamp    Furniture   west         9    320      64
5  07-11-2026      Headphone   Appliances   east         5    900     180
6  08-11-2026    Printer Jet  Electronics  north         6    400      80
7  09-11-2026       Sofa set    Furniture  south         8   1500     300
8  10-11-2026    Blender Max   Appliances   east         4    560     112
9  11-11-2026       Monitor   Electronics   west        10    900     180

In [11]:
df['Region']=df['Region'].fillna(df['Region'].mode()[0])
print(df)

   Order Date        Product     Category Region  Quantity  Sales  Profit
0  02-11-2026  Laptop Pro 15  Electronics   east         3   4500     900
1  03-10-2026          Chair    Furniture   west         7   1250     250
2  04-06-2026   Smartphone X    Appliance  north         5   7000    1400
3  05-05-2026   Coffee Maker    Appliance  south         8    600     120
4  06-11-2026      Desk Lamp    Furniture   west         9    320      64
5  07-11-2026      Headphone   Appliances   east         5    900     180
6  08-11-2026    Printer Jet  Electronics  north         6    400      80
7  09-11-2026       Sofa set    Furniture  south         8   1500     300
8  10-11-2026    Blender Max   Appliances   east         4    560     112
9  11-11-2026       Monitor   Electronics   west        10    900     180

In [13]:
### Handling missing  Numerical& Outliers
import pandas as pd
df=pd.read_csv("Retail sales.csv")
df['Sales']=df['Sales'].fillna(df['Sales'].mean())
df['Region']=df['Region'].fillna(df['Region'].mode()[0])
print(df)

   Order Date        Product     Category Region  Quantity  Sales  Profit
0  02-11-2026  Laptop Pro 15  Electronics   east         3   4500     900
1  03-10-2026          Chair    Furniture   west         7   1250     250
2  04-06-2026   Smartphone X    Appliance  north         5   7000    1400
3  05-05-2026   Coffee Maker    Appliance  south         8    600     120
4  06-11-2026      Desk Lamp    Furniture   west         9    320      64
5  07-11-2026      Headphone   Appliances   east         5    900     180
6  08-11-2026    Printer Jet  Electronics  north         6    400      80
7  09-11-2026       Sofa set    Furniture  south         8   1500     300
8  10-11-2026    Blender Max   Appliances   east         4    560     112
9  11-11-2026       Monitor   Electronics   west        10    900     180

In [14]:
df=pd.read_csv("Retail sales.csv")
df.duplicated().sum()
#df.drop_duplicates(inplace=True)

np.int64(0)

In [16]:
df=pd.read_csv("Retail sales.csv")
df.duplicated().sum()
df.drop_duplicates(inplace=True)
df

   Order Date        Product     Category Region  Quantity  Sales  Profit
0  02-11-2026  Laptop Pro 15  Electronics   east         3   4500     900
1  03-10-2026          Chair    Furniture   west         7   1250     250
2  04-06-2026   Smartphone X    Appliance  north         5   7000    1400
3  05-05-2026   Coffee Maker    Appliance  south         8    600     120
4  06-11-2026      Desk Lamp    Furniture   west         9    320      64
5  07-11-2026      Headphone   Appliances   east         5    900     180
6  08-11-2026    Printer Jet  Electronics  north         6    400      80
7  09-11-2026       Sofa set    Furniture  south         8   1500     300
8  10-11-2026    Blender Max   Appliances   east         4    560     112
9  11-11-2026       Monitor   Electronics   west        10    900     180

In [20]:
###
###STEP 1:LOAD &CLEAN DATA
import pandas as pd
df=pd.read_csv("Retail sales.csv")
df.drop_duplicates()
df.fillna(0)
df["Order Date"]=pd.to_datetime(df["Order Date"])
df

  Order Date        Product     Category Region  Quantity  Sales  Profit
0 2026-02-11  Laptop Pro 15  Electronics   east         3   4500     900
1 2026-03-10          Chair    Furniture   west         7   1250     250
2 2026-04-06   Smartphone X    Appliance  north         5   7000    1400
3 2026-05-05   Coffee Maker    Appliance  south         8    600     120
4 2026-06-11      Desk Lamp    Furniture   west         9    320      64
5 2026-07-11      Headphone   Appliances   east         5    900     180
6 2026-08-11    Printer Jet  Electronics  north         6    400      80
7 2026-09-11       Sofa set    Furniture  south         8   1500     300
8 2026-10-11    Blender Max   Appliances   east         4    560     112
9 2026-11-11       Monitor   Electronics   west        10    900     180

In [21]:
###STEP:2 FEATURE ENGINEERING:DATA EXTRACTION
df["Year"]=df["Order Date"].dt.year
df["Month"]=df["Order Date"].dt.month
df["Day"]=df["Order Date"].dt.day
df["Weekday"]=df["Order Date"].dt.weekday
df

,Order Date,Product,Category,Region,Quantity,Sales,Profit,Year,Month,Day,Weekday
0,2026-02-11,Laptop Pro 15,Electronics,east,3,4500,900,2026,2,11,2
1,2026-03-10,Chair,Furniture,west,7,1250,250,2026,3,10,1
2,2026-04-06,Smartphone X,Appliance,north,5,7000,1400,2026,4,6,0
3,2026-05-05,Coffee Maker,Appliance,south,8,600,120,2026,5,5,1
4,2026-06-11,Desk Lamp,Furniture,west,9,320,64,2026,6,11,3
5,2026-07-11,Headphone,Appliances,east,5,900,180,2026,7,11,5
6,2026-08-11,Printer Jet,Electronics,north,6,400,80,2026,8,11,1
7,2026-09-11,Sofa set,Furniture,south,8,1500,300,2026,9,11,4
8,2026-10-11,Blender Max,Appliances,east,4,560,112,2026,10,11,6
9,2026-11-11,Monitor,Electronics,west,10,900,180,2026,11,11,2

In [24]:
#STEP3: CATEGORICAL ENCODING
#ENCODE CATEGORY&REGION
df=pd.read_csv("Retail sales.csv")
df_encoded=pd.get_dummies(df,columns=["Product","Region"])#,drop_first=True#)
df_encoded

,Order Date,Category,Quantity,Sales,Profit,Product_Blender Max,Product_Chair,Product_Coffee Maker,Product_Desk Lamp,Product_Headphone,Product_Laptop Pro 15,Product_Monitor,Product_Printer Jet,Product_Smartphone X,Product_Sofa set,Region_east,Region_north,Region_south,Region_west
0,02-11-2026,Electronics,3,4500,900,False,False,False,False,False,True,False,False,False,False,True,False,False,False
1,03-10-2026,Furniture,7,1250,250,False,True,False,False,False,False,False,False,False,False,False,False,False,True
2,04-06-2026,Appliance,5,7000,1400,False,False,False,False,False,False,False,False,True,False,False,True,False,False
3,05-05-2026,Appliance,8,600,120,False,False,True,False,False,False,False,False,False,False,False,False,True,False
4,06-11-2026,Furniture,9,320,64,False,False,False,True,False,False,False,False,False,False,False,False,False,True
5,07-11-2026,Appliances,5,900,180,False,False,False,False,True,False,False,False,False,False,True,False,False,False
6,08-11-2026,Electronics,6,400,80,False,False,False,False,False,False,False,True,False,False,False,True,False,False
7,09-11-2026,Furniture,8,1500,300,False,False,False,False,False,False,False,False,False,True,False,False,True,False
8,10-11-2026,Appliances,4,560,112,True,False,False,False,False,False,False,False,False,False,True,False,False,False
9,11-11-2026,Electronics,10,900,180,False,False,False,False,False,False,True,False,False,False,False,False,False,True

In [26]:
#STEP3: CATEGORICAL ENCODING
#ENCODE CATEGORY&REGION
df=pd.read_csv("Retail sales.csv")
df_encoded=pd.get_dummies(df,columns=["Product","Region"],drop_first=True)
df_encoded

,Order Date,Category,Quantity,Sales,Profit,Product_Chair,Product_Coffee Maker,Product_Desk Lamp,Product_Headphone,Product_Laptop Pro 15,Product_Monitor,Product_Printer Jet,Product_Smartphone X,Product_Sofa set,Region_north,Region_south,Region_west
0,02-11-2026,Electronics,3,4500,900,False,False,False,False,True,False,False,False,False,False,False,False
1,03-10-2026,Furniture,7,1250,250,True,False,False,False,False,False,False,False,False,False,False,True
2,04-06-2026,Appliance,5,7000,1400,False,False,False,False,False,False,False,True,False,True,False,False
3,05-05-2026,Appliance,8,600,120,False,True,False,False,False,False,False,False,False,False,True,False
4,06-11-2026,Furniture,9,320,64,False,False,True,False,False,False,False,False,False,False,False,True
5,07-11-2026,Appliances,5,900,180,False,False,False,True,False,False,False,False,False,False,False,False
6,08-11-2026,Electronics,6,400,80,False,False,False,False,False,False,True,False,False,True,False,False
7,09-11-2026,Furniture,8,1500,300,False,False,False,False,False,False,False,False,True,False,True,False
8,10-11-2026,Appliances,4,560,112,False,False,False,False,False,False,False,False,False,False,False,False
9,11-11-2026,Electronics,10,900,180,False,False,False,False,False,True,False,False,False,False,False,True

In [27]:
##STEP:4 BUSINESS FEATURE CREATION(REAL-WORLD)
### 1.PROFIT MARGIN

df_encoded["Profit Margin"]=df_encoded["Profit"] / df_encoded["Sales"]
df_encoded["Profit Margin"].fillna(0)
df_encoded

,Order Date,Category,Quantity,Sales,Profit,Product_Chair,Product_Coffee Maker,Product_Desk Lamp,Product_Headphone,Product_Laptop Pro 15,Product_Monitor,Product_Printer Jet,Product_Smartphone X,Product_Sofa set,Region_north,Region_south,Region_west,Profit Margin
0,02-11-2026,Electronics,3,4500,900,False,False,False,False,True,False,False,False,False,False,False,False,0.2
1,03-10-2026,Furniture,7,1250,250,True,False,False,False,False,False,False,False,False,False,False,True,0.2
2,04-06-2026,Appliance,5,7000,1400,False,False,False,False,False,False,False,True,False,True,False,False,0.2
3,05-05-2026,Appliance,8,600,120,False,True,False,False,False,False,False,False,False,False,True,False,0.2
4,06-11-2026,Furniture,9,320,64,False,False,True,False,False,False,False,False,False,False,False,True,0.2
5,07-11-2026,Appliances,5,900,180,False,False,False,True,False,False,False,False,False,False,False,False,0.2
6,08-11-2026,Electronics,6,400,80,False,False,False,False,False,False,True,False,False,True,False,False,0.2
7,09-11-2026,Furniture,8,1500,300,False,False,False,False,False,False,False,False,True,False,True,False,0.2
8,10-11-2026,Appliances,4,560,112,False,False,False,False,False,False,False,False,False,False,False,False,0.2
9,11-11-2026,Electronics,10,900,180,False,False,False,False,False,True,False,False,False,False,False,True,0.2

In [28]:
##STEP:4 BUSINESS FEATURE CREATION(REAL-WORLD)
####2.HIFH-PROFIT LABEL(CLASSIFICATION TARGET)
df_encoded["High_Profit"]=df_encoded["Profit"].apply(lambda x:1 if x>df_encoded["Profit"].median() else 0)
df_encoded

,Order Date,Category,Quantity,Sales,Profit,Product_Chair,Product_Coffee Maker,Product_Desk Lamp,Product_Headphone,Product_Laptop Pro 15,Product_Monitor,Product_Printer Jet,Product_Smartphone X,Product_Sofa set,Region_north,Region_south,Region_west,Profit Margin,High_Profit
0,02-11-2026,Electronics,3,4500,900,False,False,False,False,True,False,False,False,False,False,False,False,0.2,1
1,03-10-2026,Furniture,7,1250,250,True,False,False,False,False,False,False,False,False,False,False,True,0.2,1
2,04-06-2026,Appliance,5,7000,1400,False,False,False,False,False,False,False,True,False,True,False,False,0.2,1
3,05-05-2026,Appliance,8,600,120,False,True,False,False,False,False,False,False,False,False,True,False,0.2,0
4,06-11-2026,Furniture,9,320,64,False,False,True,False,False,False,False,False,False,False,False,True,0.2,0
5,07-11-2026,Appliances,5,900,180,False,False,False,True,False,False,False,False,False,False,False,False,0.2,0
6,08-11-2026,Electronics,6,400,80,False,False,False,False,False,False,True,False,False,True,False,False,0.2,0
7,09-11-2026,Furniture,8,1500,300,False,False,False,False,False,False,False,False,True,False,True,False,0.2,1
8,10-11-2026,Appliances,4,560,112,False,False,False,False,False,False,False,False,False,False,False,False,0.2,0
9,11-11-2026,Electronics,10,900,180,False,False,False,False,False,True,False,False,False,False,False,True,0.2,0

In [30]:
###### STEP:5 FEATURE SCALING(ML ESSENTIAL)

from sklearn.preprocessing import StandardScaler
#df=pd.read_csv(r"C:\Users\DELL\Downloads\Retail_sales.csv")
scaler=StandardScaler()
num_cols=["Quantity","Sales","Profit","Profit Margin"]
df_encoded[num_cols]=scaler.fit_transform(df_encoded[num_cols])
df_encoded

,Order Date,Category,Quantity,Sales,Profit,Product_Chair,Product_Coffee Maker,Product_Desk Lamp,Product_Headphone,Product_Laptop Pro 15,Product_Monitor,Product_Printer Jet,Product_Smartphone X,Product_Sofa set,Region_north,Region_south,Region_west,Profit Margin,High_Profit
0,02-11-2026,Electronics,-1.623086,1.298355,1.298355,False,False,False,False,True,False,False,False,False,False,False,False,0.0,1
1,03-10-2026,Furniture,0.231869,-0.260438,-0.260438,True,False,False,False,False,False,False,False,False,False,False,True,0.0,1
2,04-06-2026,Appliance,-0.695608,2.497426,2.497426,False,False,False,False,False,False,False,True,False,True,False,False,0.0,1
3,05-05-2026,Appliance,0.695608,-0.572197,-0.572197,False,True,False,False,False,False,False,False,False,False,True,False,0.0,0
4,06-11-2026,Furniture,1.159347,-0.706493,-0.706493,False,False,True,False,False,False,False,False,False,False,False,True,0.0,0
5,07-11-2026,Appliances,-0.695608,-0.428308,-0.428308,False,False,False,True,False,False,False,False,False,False,False,False,0.0,0
6,08-11-2026,Electronics,-0.231869,-0.668123,-0.668123,False,False,False,False,False,False,True,False,False,True,False,False,0.0,0
7,09-11-2026,Furniture,0.695608,-0.140531,-0.140531,False,False,False,False,False,False,False,False,True,False,True,False,0.0,1
8,10-11-2026,Appliances,-1.159347,-0.591382,-0.591382,False,False,False,False,False,False,False,False,False,False,False,False,0.0,0
9,11-11-2026,Electronics,1.623086,-0.428308,-0.428308,False,False,False,False,False,True,False,False,False,False,False,True,0.0,0

In [35]:
###### STEP 6:FEATURE & TARGRT SELECTION
### REGRESSION
X=df_encoded.drop(["Sales","Order Date"],axis=1)
Y=df_encoded["Sales"]
df_encoded

,Order Date,Category,Quantity,Sales,Profit,Product_Chair,Product_Coffee Maker,Product_Desk Lamp,Product_Headphone,Product_Laptop Pro 15,Product_Monitor,Product_Printer Jet,Product_Smartphone X,Product_Sofa set,Region_north,Region_south,Region_west,Profit Margin,High_Profit
0,02-11-2026,Electronics,-1.623086,1.298355,1.298355,False,False,False,False,True,False,False,False,False,False,False,False,0.0,1
1,03-10-2026,Furniture,0.231869,-0.260438,-0.260438,True,False,False,False,False,False,False,False,False,False,False,True,0.0,1
2,04-06-2026,Appliance,-0.695608,2.497426,2.497426,False,False,False,False,False,False,False,True,False,True,False,False,0.0,1
3,05-05-2026,Appliance,0.695608,-0.572197,-0.572197,False,True,False,False,False,False,False,False,False,False,True,False,0.0,0
4,06-11-2026,Furniture,1.159347,-0.706493,-0.706493,False,False,True,False,False,False,False,False,False,False,False,True,0.0,0
5,07-11-2026,Appliances,-0.695608,-0.428308,-0.428308,False,False,False,True,False,False,False,False,False,False,False,False,0.0,0
6,08-11-2026,Electronics,-0.231869,-0.668123,-0.668123,False,False,False,False,False,False,True,False,False,True,False,False,0.0,0
7,09-11-2026,Furniture,0.695608,-0.140531,-0.140531,False,False,False,False,False,False,False,False,True,False,True,False,0.0,1
8,10-11-2026,Appliances,-1.159347,-0.591382,-0.591382,False,False,False,False,False,False,False,False,False,False,False,False,0.0,0
9,11-11-2026,Electronics,1.623086,-0.428308,-0.428308,False,False,False,False,False,True,False,False,False,False,False,True,0.0,0

In [37]:
##### CLASSIFICATION
X=df_encoded.drop(["High_Profit","Order Date"],axis=1)
Y=df_encoded["High_Profit"]
df_encoded

,Order Date,Category,Quantity,Sales,Profit,Product_Chair,Product_Coffee Maker,Product_Desk Lamp,Product_Headphone,Product_Laptop Pro 15,Product_Monitor,Product_Printer Jet,Product_Smartphone X,Product_Sofa set,Region_north,Region_south,Region_west,Profit Margin,High_Profit
0,02-11-2026,Electronics,-1.623086,1.298355,1.298355,False,False,False,False,True,False,False,False,False,False,False,False,0.0,1
1,03-10-2026,Furniture,0.231869,-0.260438,-0.260438,True,False,False,False,False,False,False,False,False,False,False,True,0.0,1
2,04-06-2026,Appliance,-0.695608,2.497426,2.497426,False,False,False,False,False,False,False,True,False,True,False,False,0.0,1
3,05-05-2026,Appliance,0.695608,-0.572197,-0.572197,False,True,False,False,False,False,False,False,False,False,True,False,0.0,0
4,06-11-2026,Furniture,1.159347,-0.706493,-0.706493,False,False,True,False,False,False,False,False,False,False,False,True,0.0,0
5,07-11-2026,Appliances,-0.695608,-0.428308,-0.428308,False,False,False,True,False,False,False,False,False,False,False,False,0.0,0
6,08-11-2026,Electronics,-0.231869,-0.668123,-0.668123,False,False,False,False,False,False,True,False,False,True,False,False,0.0,0
7,09-11-2026,Furniture,0.695608,-0.140531,-0.140531,False,False,False,False,False,False,False,False,True,False,True,False,0.0,1
8,10-11-2026,Appliances,-1.159347,-0.591382,-0.591382,False,False,False,False,False,False,False,False,False,False,False,False,0.0,0
9,11-11-2026,Electronics,1.623086,-0.428308,-0.428308,False,False,False,False,False,True,False,False,False,False,False,True,0.0,0

In [38]:
##STEP 7:EXPORT ML-READY DATASET
df_encoded.to_csv("Retail_sales.csv",index=False)